Верстка главной и каталога
htmlacademy-htmlcss/287893-gllacy-31 pull request #4
Opened 2021-05-27 11:13 UTC by Tanyakiss

Домашняя работа по разметке

2021-05-27 21:46 UTC, mikhin requested changes

2021-05-27 21:46 UTC, mikhin commented on blank.html
> +      <nav>
Сейчас в главную навигацию входит слишком много того, что вообще не является навигацией =) Обычно главная навигация — это меню основных разделов сайта. Давай поправим?)

2021-05-27 21:46 UTC, mikhin commented on blank.html
> +        <a href="blank.html"></a>
Непонятная ссылка) Это зачем?)

2021-05-27 21:46 UTC, mikhin commented on blank.html
> +        <a href="blank.html">Вход</a>
Для этих элементов тоже нужен список)

2021-05-27 21:46 UTC, mikhin commented on blank.html
> +        с 10 до 20 ежедневно
Любой текст всегда должен быть как-то размечен семантически)

2021-05-27 21:46 UTC, mikhin commented on blank.html
> +      <section>
`section` — это тег, в котором должен содержаться какой-то контент, полезный пользователю, за которым он прям пришел =) это типа как глава в книге) вот эта штука тут, врядли прям истинно полезный контент для пользователя)

если что — не бойся использовать дивы)

2021-05-27 21:46 UTC, mikhin commented on blank.html
> +            <img src="https://via.placeholder.com/15x13" alt="Иконка сердце" >
Давай все декоративные или интерфейсные картинки сделаем потом через CSS?) Обычно интерфейсные изображения не должны быть в разметке документа)

2021-05-27 21:46 UTC, mikhin commented on blank.html
> +      <nav>
Это вроде бы не похоже на ГЛАВНУЮ навигацию для сайта =) тем более одна у нас уже есть в шапке)

2021-05-27 21:46 UTC, mikhin commented on blank.html
> +      <section>
Тут тоже маловато полезного контента для section)

2021-05-27 21:46 UTC, mikhin commented on blank.html
> +          <a href="https://htmlacademy.ru">Сделано в HTML Academy &copy; 2021</a>
лайк за мнемонику &copy;

2021-05-27 21:46 UTC, mikhin commented on catalog.html
> +            <input type="radio">0%
нужен еще атрибут name

2021-05-27 21:46 UTC, mikhin commented on catalog.html
> +            <input type="checkbox" checked>шоколадные
нужен еще атрибут name

2021-05-27 21:46 UTC, mikhin commented on catalog.html
> +        <h2>Меню</h2>
Хм, а разве это меню?)

2021-05-27 21:46 UTC, mikhin commented on catalog.html
> +            <li>
В каждой карточке еще есть кнопка «Быстрый просмотр»

2021-05-27 21:46 UTC, mikhin commented on catalog.html
> +              <a>2</a>
Если нет атрибута href, то это уже не ссылка) например, это может быть span)

2021-05-27 21:46 UTC, mikhin commented on index.html
> +          <img src="https://via.placeholder.com/367x582" alt="Пломбир с помадкой и клубничный щербет">
Пока не очень понял идею с двумя изображениями. Зачем они нужны?)

Тут еще нужно разметить остальные слайды, ведь всего их 3)

2021-05-27 21:46 UTC, mikhin commented on index.html
> +        <nav>
nav — это тег именно для основной навигации по сайту, обычно она встречается единожды на странице)

2021-05-27 21:46 UTC, mikhin commented on index.html
> +      <section>
Давай тут сделаем div?)

2021-05-27 21:46 UTC, mikhin commented on index.html
> +        <button type="submit">Хочу варенье!</button>
Тут нет формы, поэтому не может быть type="submit")

2021-05-27 21:46 UTC, mikhin commented on index.html
> +      <section>
Маловато полезного контента для section)

2021-05-27 21:46 UTC, mikhin commented on index.html
> +      <section>
Давай тут тоже сделаем div?)

2021-05-27 21:46 UTC, mikhin commented on index.html
> +        <button type="submit">Форма обратной связи</button>
Тут тоже не может быть type=submit

2021-05-27 21:46 UTC, mikhin commented on styleguade.html
> +<html lang="ru">
Стайлгайд верстать не нужно, поэтому эта страница не нужна)

2021-05-31 14:45 UTC, Tanyakiss commented on blank.html
> +      <nav>
Исправлено

2021-05-31 14:46 UTC, Tanyakiss commented on blank.html
> +        <a href="blank.html"></a>
Исправлено

2021-05-31 14:46 UTC, Tanyakiss commented on blank.html
> +        <a href="blank.html">Вход</a>
Исправлено

2021-05-31 14:46 UTC, Tanyakiss commented on blank.html
> +        с 10 до 20 ежедневно
Исправлено

2021-05-31 14:46 UTC, Tanyakiss commented on blank.html
> +      <section>
Исправлено

2021-05-31 14:46 UTC, Tanyakiss commented on index.html
> +        <button type="submit">Хочу варенье!</button>
Исправлено

2021-05-31 14:46 UTC, Tanyakiss commented on index.html
> +      <section>
Исправлено

2021-05-31 14:46 UTC, Tanyakiss commented on index.html
> +      <section>
Исправлено

2021-05-31 14:46 UTC, Tanyakiss commented on index.html
> +        <button type="submit">Форма обратной связи</button>
Исправлено

2021-05-31 14:46 UTC, Tanyakiss commented on styleguade.html
> +<html lang="ru">
Исправлено

2021-05-31 21:21 UTC, mikhin approved these changes

2021-05-31 21:21 UTC, mikhin commented on blank.html
> -<!DOCTYPE html>
@Tanyakiss , а почему удалила файл?)

2021-05-31 21:21 UTC, mikhin commented on index.html
> +        <nav>
@Tanyakiss , тут не исправила)

2021-05-31 21:21 UTC, mikhin commented on index.html
> +      <section>
@Tanyakiss , тут не исправила)

2021-05-31 21:21 UTC, mikhin commented on index.html
> +      <section>
@Tanyakiss , тут не исправила)

2021-05-31 21:21 UTC, merged

2021-06-01 05:03 UTC, Tanyakiss commented on blank.html
> -<!DOCTYPE html>
так он же не надо

2021-06-01 05:05 UTC, Tanyakiss commented on blank.html
> -<!DOCTYPE html>
в видео на эту страницу ведут ссылки, которых нету. Я заглушку поставила href="#"